ALTER TABLE PRODUTO ADD TIPO_PRODUTO SMALLINT DEFAULT 0 NOT NULL;

COMMENT ON COLUMN PRODUTO.TIPO_PRODUTO IS
'00 - Produto Acabado
01 - Semi-Acabado
02 - Matéria Prima
03 - Material Uso Consumo
04 - Ativo Imobilizado
05 - Serviços
06 - Serviços de Terceiros
07 - Outros Insumos
08 - Outros';

CREATE TABLE PRODUTO_ESTRUTURA (
    ID_ESTP INTEGER NOT NULL,
    ID_PRO INTEGER NOT NULL,
    QUANTIDADE NUMERIC(10,5) DEFAULT 0 NOT NULL);

ALTER TABLE PRODUTO_ESTRUTURA ADD CONSTRAINT PK_PRODUTO_ESTRUTURA PRIMARY KEY (ID_ESTP);
ALTER TABLE PRODUTO_ESTRUTURA ADD CONSTRAINT FK_PRODUTO_ESTRUTURA_PRO FOREIGN KEY (ID_PRO) REFERENCES PRODUTO(ID_PRO) ON DELETE CASCADE;

CREATE SEQUENCE GEN_ESTP;

SET TERM ^ ;

CREATE TRIGGER BI_PRODUTO_ESTRUTURA_GID FOR PRODUTO_ESTRUTURA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (COALESCE(NEW.ID_ESTP, 0) = 0) THEN
    NEW.ID_ESTP = GEN_ID(GEN_ESTP,1);
END^

SET TERM ; ^

CREATE GENERATOR GEN_OPRO;

CREATE TABLE ORDEM_PRODUCAO (
    ID_OPRO          INTEGER NOT NULL,
    DESCRICAO        VARCHAR(100) NOT NULL,
    ID_EMP           DOM_ID_EMPRESA NOT NULL /* DOM_ID_EMPRESA = BIGINT NOT NULL */,
	DATA_CREATED 	 TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DATA_INIC_PREV   TIMESTAMP NOT NULL,
    DATA_FINAL_PREV  TIMESTAMP NOT NULL,
    OBSERVACAO       VARCHAR(500),
	STATUS 			 SMALLINT DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN ORDEM_PRODUCAO.STATUS IS
'0 = ATIVO
1 = PAUSADO
2 = INATIVO';

ALTER TABLE ORDEM_PRODUCAO ADD CONSTRAINT PK_ORDEM_PRODUCAO PRIMARY KEY (ID_OPRO);
ALTER TABLE ORDEM_PRODUCAO ADD CONSTRAINT FK_ORDEM_PRODUCAO_EMP FOREIGN KEY (ID_EMP) REFERENCES EMPRESA (ID_EMP);

SET TERM ^ ;
CREATE OR ALTER TRIGGER BI_ORDEM_PRODUCAO_GID FOR ORDEM_PRODUCAO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (COALESCE(NEW.ID_OPRO, 0) = 0) THEN
    NEW.ID_OPRO = GEN_ID(GEN_OPRO,1);
END^

SET TERM ; ^

CREATE TABLE ORDEM_PRODUCAO_ITEM (
    ID_OPROI INTEGER NOT NULL,
    ID_OPRO INTEGER NOT NULL,
    ID_PRO INTEGER NOT NULL,
    QUANTIDADE NUMERIC(10,5) DEFAULT 0 NOT NULL,
    LOTE_NUMERO VARCHAR(20),
    FABRICACAO DATE,
    VALIDADE DATE,
    OBSERVACAO VARCHAR(500));

ALTER TABLE ORDEM_PRODUCAO_ITEM ADD CONSTRAINT PK_ORDEM_PRODUCAO_ITEM PRIMARY KEY (ID_OPROI);

CREATE SEQUENCE GEN_OPROI;

SET TERM ^ ;

CREATE TRIGGER BI_ORDEM_PRODUCAO_ITEM_GID FOR ORDEM_PRODUCAO_ITEM
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (COALESCE(NEW.ID_OPROI, 0) = 0) THEN
    NEW.ID_OPROI = GEN_ID(GEN_OPROI,1);
END^

SET TERM ; ^

ALTER TABLE ORDEM_PRODUCAO_ITEM ADD CONSTRAINT FK_ORDEM_PRODUCAO_ITEM_PRO FOREIGN KEY (ID_PRO) REFERENCES PRODUTO(ID_PRO);

DROP VIEW VW_ORDEM_PRODUCAO_ITEM;

CREATE VIEW VW_ORDEM_PRODUCAO_ITEM(
    ID_OITEM,
    ID_ORDEM,
    ID_PRO,
    QUANTIDADE,
    LOTE_NUMERO,
    FABRICACAO,
    VALIDADE,
    OBSERVACAO,
    DATA_INIC_PREV,
    DATA_FINAL_PREV,
    DATA_INIC_REAL,
    DATA_FINAL_REAL,
    STATUS,
    DESCRICAO,
    CUSTO_UNIT,
    CUSTO_KG,
    CUSTO_TOTAL,
    EMBALAGEM)
AS
SELECT ORDEM_PRODUCAO_ITEM.ID_OITEM,
       ORDEM_PRODUCAO_ITEM.ID_ORDEM,
       ORDEM_PRODUCAO_ITEM.ID_PRO,
       ORDEM_PRODUCAO_ITEM.QUANTIDADE,
       ORDEM_PRODUCAO_ITEM.LOTE_NUMERO,
       ORDEM_PRODUCAO_ITEM.FABRICACAO,
       ORDEM_PRODUCAO_ITEM.VALIDADE,
       ORDEM_PRODUCAO_ITEM.OBSERVACAO,
       ORDEM_PRODUCAO_ITEM.DATA_INIC_PREV,
       ORDEM_PRODUCAO_ITEM.DATA_FINAL_PREV,
       ORDEM_PRODUCAO_ITEM.DATA_INIC_REAL,
       ORDEM_PRODUCAO_ITEM.DATA_FINAL_REAL,
       ORDEM_PRODUCAO_ITEM.STATUS,
       PRODUTO.DESCRICAO,
       ORDEM_PRODUCAO_ITEM.CUSTO_UNIT,
       ORDEM_PRODUCAO_ITEM.CUSTO_KG,
       ORDEM_PRODUCAO_ITEM.CUSTO_TOTAL,
       EMBAL.DESCRICAO
FROM ORDEM_PRODUCAO_ITEM
JOIN PRODUTO ON (ORDEM_PRODUCAO_ITEM.ID_PRO = PRODUTO.ID_PRO)
JOIN EMBAL   ON (EMBAL.ID_EMB               = PRODUTO.ID_EMB)
;

GRANT SELECT, UPDATE, DELETE, INSERT, REFERENCES ON VW_ORDEM_PRODUCAO_ITEM TO FORCA_V;

GRANT SELECT, UPDATE, DELETE, INSERT, REFERENCES ON VW_ORDEM_PRODUCAO_ITEM TO ROLE_ADMIN WITH GRANT OPTION;

CREATE INDEX IDX_NFISCAL_SAIDA ON NFISCAL (ENTR_SAIDA);
CREATE INDEX IDX_NFISCAL_EMISSAO ON NFISCAL (EMISSAO);



