SET TERM ^ ;

CREATE OR ALTER TRIGGER AU_ORDEM_PRODUCAO_ITEM_ESTOQUE FOR ORDEM_PRODUCAO_ITEM
ACTIVE AFTER UPDATE POSITION 0
AS
DECLARE ENTRADA         SMALLINT = 0;
DECLARE NAT_PRODUCAO    SMALLINT = 7;
DECLARE ID_EMP          BIGINT;
DECLARE STATUS_FINISHED SMALLINT = 2;
BEGIN
    IF ((UPDATING) AND (NEW.STATUS <> OLD.STATUS) AND (NEW.STATUS = :STATUS_FINISHED)) THEN BEGIN
        SELECT ORDEM_PRODUCAO.ID_EMP
          FROM ORDEM_PRODUCAO
         WHERE ORDEM_PRODUCAO.ID_ORDEM = NEW.ID_ORDEM
          INTO :ID_EMP;

        EXECUTE PROCEDURE SP_CTRL_ESTOQUE(NEW.ID_OITEM, :NAT_PRODUCAO, :ID_EMP, NEW.ID_PRO, NEW.QUANTIDADE, CURRENT_DATE, :ENTRADA, NULL);
    END
END^

SET TERM ; ^

